---

# Set Commons facts for RedHat or CentOS
- name: ({{ ansible_distribution }}) - INIT - Define commons facts for for RedHat or CentOS installation
  set_fact:
   packages: "{{ (packages | default([])) + ['epel-release', 'sshfs', 'fuse', 'fuse-libs', 'glusterfs', \
    'glusterfs-fuse', 'attr'] }}"
  when:
   - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

# Set Commons facts for Ubuntu
- name: ({{ ansible_distribution }}) - INIT - Define commons facts for for Ubuntu installation
  set_fact:
   packages: "{{ (packages | default([])) + ['fuse', 'libfuse2', 'sshfs', 'fuse-sshfs ', 'fusesmb', \
   'glusterfs-client'] }}"
  when:
   - ansible_distribution == "Ubuntu"
