---

# Ensure Required Packages are installed
- name: ({{ ansible_distribution }}) - INSTALL - Ensure Required Packages are installed
  package:
   name: "{{ item }}"
   state: present
  loop: "{{ server_packages }}"
  when:
   - item != "firewalld" or ansible_distribution != "CentOS" or distribution_major_version|int > 6
