---

# Install packages for Ubuntu
- name: ({{ ansible_distribution }}) - INSTALL - Install packages for Ubuntu
  apt:
   name: "{{ item }}"
   update_cache: true
   force_apt_get: true
   state: present
  loop: "{{ packages }}"
  when:
   - ansible_distribution == "Ubuntu"

# Install packages for CentOS/RedHat
- name: ({{ ansible_distribution }}) - INSTALL - Install packages for CentOS/RedHat
  yum:
   name: "{{ item }}"
   update_cache: true
   state: present
  loop: "{{ packages }}"
  when:
   - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
