---

# Ensure Required Packages are installed
- name: ({{ ansible_distribution }}) - INSTALL - Ensure Required Packages are installed
  package:
   name: "{{ item }}"
   state: present
  loop: "{{ server_packages }}"
  when:
   - item != 'firwalld' or (ansible_distribution != 'CentOS' or distribution_major_version|int > 6)
