---
- name: Converge
  hosts: all
  no_log: false

  tasks:

   - name: "Execute init server ansible role"
     include_role:
      name: ansible-role-initserver
     vars:
      server_app_code: "kis"
      server_password_auth: true
      server_app_description: "KubeCloud Application description"
      server_app_home: "/kubecloud/myapp/"
      server_user_name: "admin"
      server_user_comment: "KIS Application Administrator"
      server_user_password: "admin123"
      server_user_groups: ["kis", "sudo", "adm", "exploit"]
      server_user_create_home: true
      server_user_shell: "/usr/bin/bash"
      server_user_ssh_private_key: "security/admin_rsa"
      server_user_autorized_keys: ["security/admin_rsa.pub"]
